# Build settings
markdown: kramdown
title: Vimwiki
author: Cristian
github_username: cristianpb
exclude:
- Gemfile

markdown_ext:         "wiki,mkdown,mkdn,mkd,md"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      type: "post"

plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
