---

# Social
github_username: cristianpb
title: Vimwiki
author: Cristian

# Exclude files to compile
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Ensure sass dir
sass:
  sass_dir: _sass

# markdown style
markdown: kramdown

# accept wiki extensions
markdown_ext: "wiki,mkdown,mkdn,mkd,md"

# mark all files as post layout
defaults:
  -
    scope:
      path: ""  # an empty string here means all files in the project
    values:
      layout: "default"
      type: "post"

# github default plugins
plugins:
  - jekyll-redirect-from
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jemoji
